# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeSigma <- function(sigma, d) {
    .Call('_mvnbart4_makeSigma', PACKAGE = 'mvnbart4', sigma, d)
}

makeSigmaInv <- function(Sigma) {
    .Call('_mvnbart4_makeSigmaInv', PACKAGE = 'mvnbart4', Sigma)
}

wishart_loglikelihood <- function(X, Sigma, nu) {
    .Call('_mvnbart4_wishart_loglikelihood', PACKAGE = 'mvnbart4', X, Sigma, nu)
}

iwishart_loglikelihood <- function(X, Sigma, nu) {
    .Call('_mvnbart4_iwishart_loglikelihood', PACKAGE = 'mvnbart4', X, Sigma, nu)
}

log_dmvn <- function(x, Sigma) {
    .Call('_mvnbart4_log_dmvn', PACKAGE = 'mvnbart4', x, Sigma)
}

cppbart <- function(x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, update_Sigma, var_selection_bool) {
    .Call('_mvnbart4_cppbart', PACKAGE = 'mvnbart4', x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, update_Sigma, var_selection_bool)
}

cppbart_CLASS <- function(x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, nu, alpha, beta, m, update_sigma, var_selection_bool) {
    .Call('_mvnbart4_cppbart_CLASS', PACKAGE = 'mvnbart4', x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, nu, alpha, beta, m, update_sigma, var_selection_bool)
}

norm_rs <- function(a, b) {
    .Call('_mvnbart4_norm_rs', PACKAGE = 'mvnbart4', a, b)
}

half_norm_rs <- function(a, b) {
    .Call('_mvnbart4_half_norm_rs', PACKAGE = 'mvnbart4', a, b)
}

unif_rs <- function(a, b) {
    .Call('_mvnbart4_unif_rs', PACKAGE = 'mvnbart4', a, b)
}

exp_rs <- function(a, b) {
    .Call('_mvnbart4_exp_rs', PACKAGE = 'mvnbart4', a, b)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call('_mvnbart4_rnorm_trunc', PACKAGE = 'mvnbart4', mu, sigma, lower, upper)
}

